### ISSUE TITLE
CSS Minification breaks CSS File order

### ISSUE THREAD

**Issue by Reflic** [yeoman/generator-backbone#104]
I have build a template block in my index.html.

```html
<!-- build:css styles/main.css -->
    <link rel="stylesheet"  href="styles/bootstrap.css">
    <link rel="stylesheet" href="styles/bootstrap-responsive.css">
    <!-- Loading Flat UI -->
    <link rel="stylesheet" href="styles/flat-ui.css">
    <link rel="stylesheet" href="styles/custom.css">
    <!-- endbuild -->
```
This should concat and minify the css files in the given order to one `main.css` File.

But it seems, that the cssmin task is changing the order. 
When disabeling the cssmin task and looking at the concated file everything is alright.

But the minified **main.css** is in the wrong order. I have checked for the right order  by but putting comments in each css file, as these are appearing on their own line.
In the minified css file the order is like this:

1. Bootstrap Responsive v2.3.2
2. Bootstrap v2.3.2
3. custom.css
4. flat-ui.css

The output of `grunt build` shows that the **cssmin** task has the following configuration: 
```
cssmin:
  { dist: 
   { files: 
      { '<%= yeoman.dist %>/styles/main.css': 
         [ '.tmp/styles/{,*/}*.css',
           'app/styles/{,*/}*.css' ] } },
  'dist/styles/main.css': 'dist/styles/main.css' }

```

Am I missing something or is this a bug?

**Comment by arthurvr** [comment]
This has been open for super long, and since this issue was opened the build pipeline has been overhauled multiple times. Because of that's we can be pretty sure that this issue doesn't exist anymore in the latest generator-backbone, so I'm going to close it.

If you still run into issues regarding the build process on the latest generator-backbone version, you can always open a new ticket with details :)
