### ISSUE TITLE
Problem when generator runs "node install",  "grunt-sass-0.18.0" does not install

### ISSUE THREAD

**Issue by gamaralf** [yeoman/generator-backbone#329]
When I run "yo backbone testapp", it fails at the "node install" step.

I edited package.json, changed  "grunt-sass-0.18.0" to  "grunt-sass-0.17.0" and now "node install" works. But the generated "system" is broken.

**Comment by lakhaNamdhari** [comment]
+1 from my side.

faced same issue, I have noticed that latest repo does have the fix ( changed "grunt-sass-0.18.0" ) but looks like its not merged with the latest release yet.

**Comment by derTobsch** [comment]
+1

**Comment by BernhardBezdek** [comment]
Having the opposite problem with latest release (0.3.5).
Only if I change grunt-sass-0.17.0 to grunt-sass-0.18.0 the npm install gets completed.

Using OSX 10.10.3 and node 0.12.2

**Comment by arthurvr** [comment]
@derTobsch @gamaralf What node version are you on?

**Comment by derTobsch** [comment]
v0.12.0

**Comment by kevva** [comment]
What does it say? It really sounds like a [node-sass](https://github.com/sass/node-sass) issue.

**Comment by derTobsch** [comment]
oh, i have no idea. I created everything by hand after that. So i do not use yeoman anymore :/

**Comment by lcb931023** [comment]
+1 with ^0.17 in config

Here's the top part of error log:
```
node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/changbaili/Code/stadiums/webappbackbone/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by lcb931023** [comment]
Mac OS 10.10.3

node v0.12.2

npm v2.7.4

**Comment by lcb931023** [comment]
grunt-sass 1.0.0 is working fiiiiiiine

**Comment by arthurvr** [comment]
@BernhardBezdek @gamaralf @derTobsch Can you try if this is fixed in master? I think this was fixed in  https://github.com/yeoman/generator-backbone/commit/267ad5d475e74ba0568a6b9a292f7aef72d205b2. If y'all can confirm that I'm going to make a new release.

You can try the generator locally by cloning the repo and running `npm link`. Then `yo backbone` will start the generator.

**Comment by BernhardBezdek** [comment]
@arthurvr it's working when using the master branch

**Comment by rjsteinert** [comment]
Hi Folks - This is an issue with running node-sass 1.x.x on node 0.12.x.  See https://github.com/sass/node-sass/issues/653 ... Whatever is requiring in node-sass needs to bump the version of node-sass to 2.x.x. I see grunt-sass just got bumped on this project (https://github.com/yeoman/generator-backbone/commit/267ad5d475e74ba0568a6b9a292f7aef72d205b2) ... Trying HEAD of master now...

**Comment by rjsteinert** [comment]
Yup, that fixed it. This issue is the same as #343. And this https://github.com/yeoman/generator-backbone/commit/267ad5d475e74ba0568a6b9a292f7aef72d205b2 fixes it. For folks who can't wait generator-backbone to provide an official release, delete the generator-backbone folder in your global node_modules directory, git clone this repo so you are on the HEAD of master, npm install, and then you should be good to go.

**Comment by arthurvr** [comment]
Let's close this as fixed on master. Thanks everybody.
