### ISSUE TITLE
Generator Failing

### ISSUE THREAD

**Issue by singh-** [yeoman/generator-backbone#369]
'yo backbone' throws an error, attached herewith.
![error](https://cloud.githubusercontent.com/assets/6245927/10274732/6134439e-6b5e-11e5-846d-665440263041.PNG)

**Comment by ruyadorno** [comment]
Hi @singh- from your logs we can see the problem occurs on the `bower install` phase and does not seems related to the code generated by this generator, therefore I'm closing this issue :blush: 

Personally, I had to deal with a similar issue in the past and it turned out to be a proxy issue within the company I used to work at the time.

Please check the issues below, there are many valuable comments on those and they might help you out

- https://github.com/bower/bower/issues/50
- https://github.com/bower/bower/issues/1574
